import { ApiCallState } from "../Utils";

export type UserAssignment = {
  id: number;
  project_id: number;
  assign_id: string;
};

export type UserAssignmentStateTypes = {
  fetchAll: ApiCallState<UserAssignment[]>;
  fetchOne: ApiCallState<UserAssignment | {}>;
};

export const UserAssignmentActionTypes = {
  FETCH_ALL_USER_ASSIGNMENT: "FETCH_ALL_USER_ASSIGNMENT",
  FETCH_ALL_USER_ASSIGNMENT_RESET: "FETCH_ALL_USER_ASSIGNMENT_RESET",
  FETCH_ALL_USER_ASSIGNMENT_FAILURE: "FETCH_ALL_USER_ASSIGNMENT_FAILURE",
  FETCH_ALL_USER_ASSIGNMENT_SUCCESS: "FETCH_ALL_USER_ASSIGNMENT_SUCCESS",

  FETCH_ONE_USER_ASSIGNMENT: "FETCH_ONE_USER_ASSIGNMENT",
  FETCH_ONE_USER_ASSIGNMENT_RESET: "FETCH_ONE_USER_ASSIGNMENT_RESET",
  FETCH_ONE_USER_ASSIGNMENT_FAILURE: "FETCH_ONE_USER_ASSIGNMENT_FAILURE",
  FETCH_ONE_USER_ASSIGNMENT_SUCCESS: "FETCH_ONE_USER_ASSIGNMENT_SUCCESS",
};
