
GET   http://localhost:4000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkFtb24gSXNheWFzIiwiZW1haWwiOiJhbW9uaXNheWFzMTIzNEBnbWFpbC5jb20iLCJjb21wYW55IjpudWxsLCJyb2xlIjoiUHJvamVjdCBNYW5hZ2VyIiwiYWNjZXNzX3R5cGUiOm51bGwsIm1vZHVsZXNfc3Vic2NyaWJlZCI6IltcIlByb2plY3RcIixcIkRvY3VtZW50XCIsXCJIdW1hbiBSZXNvdXJjZVwiLFwiUHJvY3VyZW1lbnRcIixcIkludmVudG9yeVwiLFwiRml4ZWQgQXNzZXRcIixcIkZpbmFuY2VcIixcIk9wZXJhdGlvblwiXSIsImlhdCI6MTY1MDU0MTM3NH0.LZceEViGauTuPUwYORT8sooaLB60aPAjqunxxayIovE

{
  "date":"2022/05/05",
  "weathercondition":"nice",
  "dailyreportdetails":[
    {
      "activityDescription":"hello",
      "from":"from",
      "to":"to"
    }
  ]
}

    

# A eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IkFtb24gSXNheWFzIiwiZW1haWwiOiJhbW9uaXNheWFzMTIzNEBnbWFpbC5jb20iLCJjb21wYW55IjpudWxsLCJyb2xlIjoiUHJvamVjdCBNYW5hZ2VyIiwiYWNjZXNzX3R5cGUiOm51bGwsIm1vZHVsZXNfc3Vic2NyaWJlZCI6IltcIlByb2plY3RcIixcIkRvY3VtZW50XCIsXCJIdW1hbiBSZXNvdXJjZVwiLFwiUHJvY3VyZW1lbnRcIixcIkludmVudG9yeVwiLFwiRml4ZWQgQXNzZXRcIixcIkZpbmFuY2VcIixcIk9wZXJhdGlvblwiXSIsImlhdCI6MTY1MDU0MTM3NH0.LZceEViGauTuPUwYORT8sooaLB60aPAjqunxxayIovE

# S eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InNhbXVlbCIsImVtYWlsIjoic2FtQGdtYWlsLmNvbSIsImNvbXBhbnkiOm51bGwsInJvbGUiOiJyb2xlIDEiLCJhY2Nlc3NfdHlwZSI6bnVsbCwibW9kdWxlc19zdWJzY3JpYmVkIjoiW1wiUHJvamVjdFwiLFwiRG9jdW1lbnRcIixcIkh1bWFuIFJlc291cmNlXCIsXCJQcm9jdXJlbWVudFwiLFwiSW52ZW50b3J5XCIsXCJGaXhlZCBBc3NldFwiLFwiRmluYW5jZVwiLFwiT3BlcmF0aW9uXCJdIiwiaWF0IjoxNjUwNTQxNDE1fQ.yHRgRq5efoUO9WW5DVtTeDk_yjQzIaI34UXYEebEu4s